In [14]:
import math
import matplotlib.pyplot as plt
import numpy as np

In [25]:
def f(x):
    return (x+2)**2 -16 * (np.exp(-(x-2)**2))
def df(x):
    return 2*x +4 + 32 * (np.exp(-(x-2)**2)) * (x-2)

def gradient_descent_step(x, eps=0.01):
    fval = f(x)
    dfval = df(x)
    return x - eps * dfval
    

In [28]:
%matplotlib inline

curvex = np.linspace(-8,8,1000)
res = list()
x = 2
prec = 0.001
while True:
    xnew = gradient_descent_step(x)
    res.append(xnew)
    if np.abs(x - xnew) <  prec or xnew > 4:
        break
    x = xnew
plt.plot(curvex, f(curvex), 'b-')
plt.plot(res, [f(r) for r in res], 'gx') 
plt.show()

In [102]:
def infer(w, f_length):
    x = np.ones((f_length.shape[0], 2))
    x[:, 0] = f_length
    return np.multiply(w, x).sum(axis=1)
def lost(w, f_length, s_length):
    x = np.ones((f_length.shape[0], 2))
    x[:, 0] = f_length
    return (s_length-np.multiply(w, x).sum(axis=1))**2

def dlost(w, f_length, s_length):
    x = np.ones((f_length.shape[0], 2))
    x[:, 0] = f_length
    firstpart = np.tile(2*np.multiply(w, x).sum(axis=1) - s_length, (2,1)).transpose()
    gradient = np.multiply(firstpart, x).sum(axis=0)
    return gradient

def gradient_descent_step(w, f_length, s_length, eps=0.01):
    fval = lost(x, f_length, s_length)
    dfval = dlost(x, f_length, s_length)
    print(w, dfval)
    return w - eps * dfval, fval.sum()



In [103]:
import sys
print(sys.path.append('/home/lxmls2017/Desktop/workspace/lxmls-toolkit'))
from lxmls.readers import galton
galton_data = galton.load()

None


In [104]:
infer

<function __main__.infer>

In [105]:
w=np.random.rand(2)
step = 1
while True:
    w, lostv = gradient_descent_step(w, galton_data[:,0], galton_data[:,1]) 
    print(w.shape)
    print(step, lostv)
    step += 1
    if step > 10:
        break

(array([ 0.7694848 ,  0.21006358]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(1, 2656920.4662648002)
(array([-110976.47500437,   -1623.20501458]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(2, 2656920.4662648002)
(array([-221953.71949354,   -3246.62009275]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(3, 2656920.4662648002)
(array([-332930.96398271,   -4870.03517091]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(4, 2656920.4662648002)
(array([-443908.20847188,   -6493.45024908]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(5, 2656920.4662648002)
(array([-554885.45296105,   -8116.86532724]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(6, 2656920.4662648002)
(array([-665862.69745022,   -9740.28040541]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(7, 2656920.4662648002)
(array([-776839.94193939,  -11363.69548357]), array([ 11097724.44891699,    162341.50781648]))
(2,)
(8, 2656920.4662648002)
(array([-887817.18

In [85]:
neww.shape, lostv

((928, 2), 2656920.4662648002)